var dishes = [
    {   "name": "Ginger lemon water",
        "type": "drink",
        "kcalories": "25",
        "protein": "0",
        "carbs": "6",
        "fat": "0",
        "ingredients": ["ginger", "sugar", "lemon"],
        "img": "img\/ginger_lemon_water.jpg"
            },
    {   "name": "Cranberry & raspberry smoothie",
        "type": "drink",
        "kcalories": "100",
        "protein": "4",
        "carbs": "17",
        "fat": "2",
        "ingredients": ["cranberry", "raspberry", "milk", "yogurt", "sugar"],
        "img": "img\/cranberry_smoothie.jpg"
            },   
    {   "name": "Banana, clementine & mango smoothie",
        "type": "drink",
        "kcalories": "124",
        "protein": "5",
        "carbs": "25",
        "fat": "1",
        "ingredients": ["clementine", "mango", "banana", "yogurt"],
        "img": "img\/banana_smoothie.jpg"
        },
    {   "name": "Blueberry & lemon pancakes",
        "type": "dessert",
        "kcalories": "69",
        "protein": "2",
        "carbs": "12",
        "fat": "1",
        "ingredients": ["flour", "soda", "honey", "blueberry", "lemon", "milk", "egg", "butter"],
        "img": "img\/blueberry_pancake.jpg"
        },
    {   "name": "Vanilla ice cream",
        "type": "dessert",
        "kcalories": "159",
        "protein": "2",
        "carbs": "9",
        "fat": "13",
        "ingredients": ["milk", "cream", "vanilla", "egg", "sugar"],
        "img": "img\/vanilla_ice_cream.jpg"
        },
    {   "name": "Fruit salad",
        "type": "dessert",
        "kcalories": "83",
        "protein": "2",
        "carbs": "18",
        "fat": "0",
        "ingredients": ["grapefruit", "orange", "apricot", "honey"],
        "img": "img\/fruit_salad.jpg"
        },
    {   "name": "Strawberry panna cotta",
        "type": "dessert",
        "kcalories": "477",
        "protein": "3",
        "carbs": "32",
        "fat": "37",
        "ingredients": ["gelatin", "cream", "milk", "sugar", "strawberry"],
        "img": "img\/strawberry_pannacotta.jpg"
        },
    {   "name": "Lemon & ginger shortbread",
        "type": "dessert",
        "kcalories": "142",
        "protein": "2",
        "carbs": "18",
        "fat": "7",
        "ingredients": ["butter", "sugar", "lemon", "ginger", "flour"],
        "img": "img\/lemon_ginger_shortbread.jpg"
        },
    {   "name": "Pistachio & cranberry cookies",
        "type": "dessert",
        "kcalories": "140",
        "protein": "2",
        "carbs": "15",
        "fat": "9",
        "ingredients": ["butter", "sugar", "flour", "pistachios", "cranberry"],
        "img": "img\/pistachio_cranberry_cookies.jpg"
        },
    {   "name": "Pancakes",
        "type": "dessert",
        "kcalories": "61",
        "protein": "3",
        "carbs": "7",
        "fat": "2",
        "ingredients": ["flour", "egg", "milk", "sunflower oil"],
        "img": "img\/pancakes.jpg"
        },
    {   "name": "Apricot & orange jam",
        "type": "dessert",
        "kcalories": "27",
        "protein": "0",
        "carbs": "6",
        "fat": "0",
        "ingredients": ["apricot", "sugar", "lemon", "orange"],
        "img": "img\/apricot_orange_jam.jpg"
        },
    {   "name": "Sunshine bars",
        "type": "dessert",
        "kcalories": "190",
        "protein": "2",
        "carbs": "22",
        "fat": "11",
        "ingredients": ["oats", "cereals", "coconut", "hazelnut", "sunflower seeds", "sesame", "pumpkin seeds", "honey", "butter"],
        "img": "img\/sunshine_bars.jpg"
        },
    {   "name": "Pistachio & milk chocolate squares",
        "type": "dessert",
        "kcalories": "342",
        "protein": "6",
        "carbs": "32",
        "fat": "22",
        "ingredients": ["pistachios", "chocolate", "sugar", "butter", "egg", "flour", "milk"],
        "img": "img\/pistachio_chocolate_squares.jpg"
        },
    {   "name": "Carrot & radish salad",
        "type": "salad",
        "kcalories": "54",
        "protein": "1",
        "carbs": "11",
        "fat": "1",
        "ingredients": ["lime", "lettuce", "carrot", "radish", "onion", "coriander"],
        "img": "img\/carrot_radish_salad.jpg"
        },
    {   "name": "Caesar salad with chicken",
        "type": "salad",
        "kcalories": "430",
        "protein": "43",
        "carbs": "15",
        "fat": "23",
        "ingredients": ["olive oil", "chicken", "lettuce", "garlic", "parmesan", "vinegar"],
        "img": "img\/caesar.jpg"
        },
    {   "name": "Spinach & watercress salad",
        "type": "salad",
        "kcalories": "185",
        "protein": "4",
        "carbs": "12",
        "fat": "13",
        "ingredients": ["vinegar", "olive oil", "spinach", "watercress", "almond", "raisin"],
        "img": "img\/spinach_salad.jpg"
        },
    {   "name": "Tomato & onion salad",
        "type": "salad",
        "kcalories": "23",
        "protein": "1",
        "carbs": "5",
        "fat": "0",
        "ingredients": ["onion", "tomato", "cucumber", "chilli", "garlic", "vinegar"],
        "img": "img\/tomato_salad.jpg"
        },
    {   "name": "Greens salad",
        "type": "salad",
        "kcalories": "43",
        "protein": "1",
        "carbs": "4",
        "fat": "2",
        "ingredients": ["lime", "apple", "onion", "cucumber", "celery", "olive oil"],
        "img": "img\/greens_salad.jpg"
        },
    {   "name": "Beetroot with watercress & apple sauce",
        "type": "salad",
        "kcalories": "87",
        "protein": "3",
        "carbs": "15",
        "fat": "2",
        "ingredients": ["beetroot", "apple", "sugar", "vinegar", "horseradish", "sour cream", "watercress"],
        "img": "img\/roasted_beets.jpg"
        },
    {   "name": "Rye bread",
        "type": "bread",
        "kcalories": "85",
        "protein": "3",
        "carbs": "17",
        "fat": "1",
        "ingredients": ["rye flour", "yeast"],
        "img": "img\/rye_bread.jpg"
        },
    {   "name": "Chicken noodle soup",
        "type": "soup",
        "kcalories": "217",
        "protein": "26",
        "carbs": "26",
        "fat": "2",
        "ingredients": ["chicken", "ginger", "garlic", "spaghetti", "sweetcorn", "mushrooms", "onion", "soy sauce"],
        "img": "img\/chicken_soup.jpg"
        },
    {   "name": "Pumpkin soup",
        "type": "soup",
        "kcalories": "316",
        "protein": "6",
        "carbs": "20",
        "fat": "24",
        "ingredients": ["pumpkin", "cream", "olive oil", "onion"],
        "img": "img\/pumpkin_soup.jpg"
        },
    {   "name": "Tomato soup",
        "type": "soup",
        "kcalories": "213",
        "protein": "8",
        "carbs": "14",
        "fat": "14",
        "ingredients": ["tomato", "pesto", "basil", "olive oil", "garlic"],
        "img": "img\/tomato_soup.jpg"
        },
    {   "name": "Broccoli soup",
        "type": "soup",
        "kcalories": "300",
        "protein": "24",
        "carbs": "14",
        "fat": "16",
        "ingredients": ["broccoli", "cream", "olive oil", "onion", "celery", "potato", "butter", "chicken"],
        "img": "img\/broccoli_soup.jpg"
        },
    {   "name": "Spiced carrot & lentil soup",
        "type": "soup",
        "kcalories": "238",
        "protein": "11",
        "carbs": "34",
        "fat": "7",
        "ingredients": ["cumin", "olive oil", "carrot", "lentil", "milk"],
        "img": "img\/carrot_soup.jpg"
        },
    {   "name": "Salmon & broccoli",
        "type": "main",
        "kcalories": "310",
        "protein": "35",
        "carbs": "3",
        "fat": "17",
        "ingredients": ["salmon", "broccoli", "lemon", "onion", "soy sauce"],
        "img": "img\/salmon_broccoli.jpg"
        },
    {   "name": "Carbonara",
        "type": "main",
        "kcalories": "575",
        "protein": "28",
        "carbs": "65",
        "fat": "24",
        "ingredients": ["spaghetti", "bacon", "olive oil", "garlic", "egg", "parmesan"],
        "img": "img\/carbonara.jpg"
        },
    {   "name": "Chicken & couscous",
        "type": "main",
        "kcalories": "275",
        "protein": "25",
        "carbs": "29",
        "fat": "7",
        "ingredients": ["couscous", "chicken", "olive oil", "courgette", "lemon"],
        "img": "img\/chicken_couscous.jpg"
        },
    {   "name": "Salmon with avocado & grapefruit",
        "type": "main",
        "kcalories": "536",
        "protein": "29",
        "carbs": "8",
        "fat": "44",
        "ingredients": ["grapefruit", "lemon", "olive oil", "avocado", "salmon"],
        "img": "img\/salmon_avocado.jpg"
        },
    {   "name": "Club sandwich",
        "type": "main",
        "kcalories": "744",
        "protein": "62",
        "carbs": "49",
        "fat": "35",
        "ingredients": ["bacon", "bread", "egg", "tomato", "chicken", "salad"],
        "img": "img\/club_sandwich.jpg"
        },
    {   "name": "Peppered fillet steak with parsley potatoes",
        "type": "main",
        "kcalories": "494",
        "protein": "35",
        "carbs": "6",
        "fat": "22",
        "ingredients": ["potato", "olive oil", "garlic", "parsley", "beef", "butter", "watercress"],
        "img": "img\/steak_potatoes.jpg"
        },
    {   "name": "Roast tomatoes",
        "type": "main",
        "kcalories": "115",
        "protein": "3",
        "carbs": "12",
        "fat": "7",
        "ingredients": ["tomato", "garlic", "thyme", "vinegar", "olive oil"],
        "img": "img\/roast_tomatoes.jpg"
        },
    {   "name": "Rice",
        "type": "main",
        "kcalories": "356",
        "protein": "7",
        "carbs": "62",
        "fat": "6",
        "ingredients": ["rice", "butter", "sunflower oil", "garlic"],
        "img": "img\/rice.jpg"
        },
    {   "name": "Roast pork with vegetable roasties",
        "type": "main",
        "kcalories": "390",
        "protein": "50",
        "carbs": "30",
        "fat": "11",
        "ingredients": ["pork", "mustard", "parsley", "thyme", "sage", "olive oil", "carrot", "potato", "onion", "garlic", "celery"],
        "img": "img\/pork_vegetables.jpg"
        },
    {   "name": "Tilapia in Thai sauce",
        "type": "main",
        "kcalories": "328",
        "protein": "28",
        "carbs": "25",
        "fat": "14",
        "ingredients": ["tilapia", "flour", "sunflower oil", "onion", "garlic", "ginger", "soy sauce", "sugar", "lime", "chilli", "basil"],
        "img": "img\/tilapia.jpg"
        },
    {   "name": "Mushroom tart",
        "type": "main",
        "kcalories": "395",
        "protein": "11",
        "carbs": "21",
        "fat": "31",
        "ingredients": ["flour", "olive oil", "mushrooms", "spinach", "egg", "milk", "cream", "cheddar", "thyme"],
        "img": "img\/mushroom_tart.jpg"
        },    
    {   "name": "Roast potatoes",
        "type": "main",
        "kcalories": "164",
        "protein": "4",
        "carbs": "27",
        "fat": "5",
        "ingredients": ["potato", "oil", "salt", "lemon"],
        "img": "img\/potatoes.jpg"
        },
    {   "name": "Aubergine with yogurt & tomato sauces",
        "type": "main",
        "kcalories": "230",
        "protein": "6",
        "carbs": "22",
        "fat": "14",
        "ingredients": ["aubergine", "olive oil", "cherry tomato", "tomato", "garlic", "yogurt", "mint"],
        "img": "img\/aubergine_yogurt_tomato.jpg"
        },
    {   "name": "Corn with coriander butter",
        "type": "main",
        "kcalories": "189",
        "protein": "4",
        "carbs": "18",
        "fat": "12",
        "ingredients": ["corn", "butter", "coriander", "garlic"],
        "img": "img\/corn.jpg"
        },
    {   "name": "Spring vegetable mix",
        "type": "main",
        "kcalories": "88",
        "protein": "6",
        "carbs": "11",
        "fat": "2",
        "ingredients": ["carrot", "green beans", "asparagus", "peas", "savoy cabbage"],
        "img": "img\/veg_mix.jpg"
        },
    {   "name": "Salt & pepper prawns",
        "type": "main",
        "kcalories": "140",
        "protein": "11",
        "carbs": "10",
        "fat": "6",
        "ingredients": ["prawn", "lime", "basil", "olive oil"],
        "img": "img\/prawns.jpg"
        },
    {   "name": "Breakfast eggs",
        "type": "main",
        "kcalories": "305",
        "protein": "11",
        "carbs": "27",
        "fat": "18",
        "ingredients": ["olive oil", "potato", "cherry tomato", "onion", "egg", "basil"],
        "img": "img\/breakfast_eggs.jpg"
        },
    {   "name": "Carrot & houmous roll-ups",
        "type": "main",
        "kcalories": "355",
        "protein": "10",
        "carbs": "37",
        "fat": "19",
        "ingredients": ["houmous", "wrap", "carrot"],
        "img": "img\/houmous_rollups.jpg"
        },
    {   "name": "Porridge",
        "type": "main",
        "kcalories": "264",
        "protein": "15",
        "carbs": "33",
        "fat": "7",
        "ingredients": ["oats", "milk", "blueberry"],
        "img": "img\/porridge.jpg"
        },
    {   "name": "Baguette",
        "type": "bread",
        "kcalories": "175",
        "protein": "6",
        "carbs": "33",
        "fat": "2",
        "ingredients": ["flour", "yeast"],
        "img": "img\/baguette.jpeg"
        },
    {   "name": "Latte",
        "type": "drink",
        "kcalories": "135",
        "protein": "9",
        "carbs": "12",
        "fat": "5",
        "ingredients": ["coffee", "milk", "sugar"],
        "img": "img\/latte.jpg"
        },
    {   "name": "Green tea",
        "type": "drink",
        "kcalories": "2",
        "protein": "0",
        "carbs": "1",
        "fat": "0",
        "ingredients": ["green tea"],
        "img": "img\/tea.jpg"
        }
];